### ISSUE TITLE
Build problem on Fedora 38

### ISSUE THREAD

**Issue by ycollet** [sjoerdvankreel/infernal-synth#5] opened 2023-07-24 19:28 UTC
When building on Fedora 38 with gcc 13,1, it looks like some headers are missing:
- tuple 
- atomic
I will post a second message with the files. I compiled infernal-synch using the "-include tuple -include atomic" CXXFLAGS.

**Comment by sjoerdvankreel** [comment] 2023-07-24 21:38
Hey. It's been a while since I did a gcc compile, so I'm not surprised it doesn't build ATM. 

Unfortunately, I have to tell you that infernal does not run on Linux. Getting a clean compile is the easy part, just add some missing includes, get rid of gcc's warnings that are a bit stricter than msvc etc. Then, (last time i checked), you end up with binaries that work fine on the audio side, but the UI doesn't work (so you have to use the host-provided ui). 

I got Linux UI to the point where it would show up and react to button changes etc, but once you closed it, it would not re-open. Together with someone from surge synth team we put a lot of testing effort into linux ui, but I just couldnt get it to work properly, so in the end I decided to strip infernal of all linux-ui code alltogether. 

That means, even if you get it to build (should be easy enough), you will end up with a "headless" plugin, which is not so good for a 1500-parameter synth. If there is ever any help from this https://forum.juce.com/t/is-it-possible-to-customize-parts-of-the-vst3-bindings/56679 issue, I might consider to give it another go. But so far, that doesn't seem likely.

Sorry to disappoint, I really hate this. I'm confident that 99% of infernal code runs just fine on linux. I've seen the ui pop up, heard the audio engine working etc etc. But, i could not get the thing into a stable piece of software on linux, so, it's back on the wish-list.

**Comment by ycollet** [comment] 2023-07-25 04:54
Thanks for this mail :)
I will post a mail on linuxaudio.com. Maybe somebody will be willing to help. I am not skilled enough to help you ...

**Comment by sjoerdvankreel** [comment] 2023-07-25 17:40
Just so you know, linuxaudio.com is down/for sale. But if you find anyone interested in getting infernal to run on linux, i'd be grateful. Obviously i'd help out as much as i can, but truth be told i'm a total noob at linux programming.

The problem with infernal+vst3+juce+linux is this: infernal is not a real juce plugin. It's just a regular vst3 plugin which uses juce for it's ui (and, it is not an easy task to convert it to a full-blown juce plugin, if at all possible). The issue is that vst3 on linux requires a plugin developer to connect vst3's abstract notion of a UI-event loop from the host side to an actual UI-event loop on the plugin side. This is to get the host + all its plugins working together as a single application, so to speak.

While the plugin side of said event loop is provided by juce as well as vstgui, the documentation of how to connect plug/host is virtually non-existent. Basically, this is what you get: https://steinbergmedia.github.io/vst3_doc/base/classSteinberg_1_1Linux_1_1IRunLoop.html. Looks simple enough, but it amounts to a couple hundred lines of must-be-thread-safe code. Basically the only real examples you have to go on, are juce's and vstgui's source code that implement this.

But again, I'm a total linux noob and I would *love* for someone to prove me wrong, and to show that this stuff is actually easy or at least doable.

**Comment by ycollet** [comment] 2023-07-25 17:43
Yes, sorry, I posted a message on [linuxmusicians.com](https://linuxmusicians.com/). Let's cross the fingers and hope that somebody will jump in :)
Thanks a lot for all this work by the way !

**Comment by sjoerdvankreel** [comment] 2023-07-25 17:59
>> Thanks a lot for all this work by the way !
Appreciated.

>> Let's cross the fingers and hope that somebody will jump in :)
I'd love for someone to help me out on this, but i have to admit, i tried infernal+linux about 2 months ago and it nearly drove me crazy. Otoh, it'd be cool if this thing would be available to more people than just windows users. So, fingers crossed indeed ;)

**Comment by sjoerdvankreel** [comment] 2023-08-13 02:08
Closing for now, since no response from linuxmusicians.com. Let me know if you find anyone, who wants to help out.

**Closed by sjoerdvankreel** 2023-08-13 02:08 UTC
